# Generated by Django 3.2.13 on 2022-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20220622_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='class_model',
            name='class_test',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
