# Generated by Django 3.2.13 on 2022-06-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_class_model_class_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_model',
            name='class_test',
        ),
    ]
